menu:
  Home: /
  Archives: /archives

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:
